### ISSUE TITLE
Support skip.

### ISSUE THREAD

**Issue by zandaqo** [jridgewell/babel-plugin-transform-incremental-dom#70]
Hi,

It's a bit puzzling that this plugin doesn't support iDOM's `skip` since the feature is instrumental in creating nested components. Is there some inherent problem with JSX or iDOM that is blocking this feature? Or is there a simpler workaround imitating `skip` in JSX that I am not aware of?

**Comment by jridgewell** [comment]
There's no direct JSX syntax that would allow you to tell the transform that you want to skip. Components are very close (and we'll likely skip inside them), but iDOM just added support for them.

**Comment by zandaqo** [comment]
In that case, I propose using `skip` attribute of an element as the signal to call skip inside the element. That is, translating this: 
```
<div skip></div>
``` 
into this: 
```
elementOpen("div");
  skip();
elementClose("div");
```

I have come up with an ad-hoc implementation in my fork, if you are interested in this approach, I can polish it up and submit a pull request.

**Comment by jridgewell** [comment]
Sure. Few points:

- `skip` is a valid attribute, so we let's use `__skip`
- We might even make it customize-able via an option
- We should skip when the tag is a component

**Comment by zandaqo** [comment]
I have updated my [commit](https://github.com/zandaqo/babel-plugin-transform-incremental-dom/commit/1551a74229fa793506ee65231c77c8f9a06d866c) to address those points. It now uses `__skip` by default, and the attribute name can be changed by setting `skipAttribute` option. Components are also skipped. Can you take a look at the code? It passes all the tests, though I'm having hard time setting up eslint, so not sure about the style.

**Comment by jridgewell** [comment]
Yah, that looks fine.
