### ISSUE TITLE
How to render radio button's checked property?

### ISSUE THREAD

**Issue by Tiendq** [jridgewell/babel-plugin-transform-incremental-dom#80]
Hi,

I tried to use this code, but `checked` is always rendered, instead only when it's `true`. It causes the radio button is always selected, even when `checked="false"`.

```
let isChecked = false;
return <label><input type="radio" name="filter1" value="name1" checked={isChecked} />Filter 1</label>;
```

**Comment by jridgewell** [comment]
This is an [upstream issue](https://github.com/google/incremental-dom/issues/239) with iDOM.
