### ISSUE TITLE
Smaller UUIDs

### ISSUE THREAD

**Issue by oravecz** [jridgewell/babel-plugin-transform-incremental-dom#85]
Is it possible to generate uuids using a sequence number, or sequence with custom prefix?

**Comment by jridgewell** [comment]
What's the problem?

> sequence number

Sequence numbers are likely to hit a user specified key, which is why I didn't use some counter. Imagine:

```jsx
var lis = [{ id: 0 }, { id: 1 }];
<ul>
  {lis.map(li => <li key=li.id />)}
</ul>
```

**Comment by oravecz** [comment]
No problem per se. I was wondering about a smaller uUID so as to be able to
minify more effectively
