### ISSUE TITLE
Why is the transpilation so different in these two cases?

### ISSUE THREAD

**Issue by oravecz** [jridgewell/babel-plugin-transform-incremental-dom#86]
I am getting two different transpilations for these two similar use cases. (At least I think they should be more similar). The inline example works, the import approach fails to render any content because the function signatures are not appropriate.

```js
return data => <div>Some Content</div>
``` 

Transpiles to a reasonable:
```js
    get: function get() {
        return function ( data ) {
            (0, _incrementalDom.elementOpen)( 'div' );
            (0, _incrementalDom.text)( 'Some Content' );
            return (0, _incrementalDom.elementClose)( 'div' );
        };
    }
```

However, when I attempt to store my JSX in an imported module, I get additional `__jsxWrapper` functions added. 

```js
> template.js
export default <div>Some Content</div>

> component.js
import template from './template'
return data => template
```

Transpiles to:
```js
var _jsxWrapper = function _jsxWrapper(func, args) {
    return {
        __jsxDOMWrapper: true,
        func: func,
        args: args
    };
};

var _div$wrapper = function _div$wrapper() {
    (0, _incrementalDom.elementOpen)("div");
    (0, _incrementalDom.text)("Some Content");
    return (0, _incrementalDom.elementClose)("div");
};

template.default = _jsxWrapper(_div$wrapper);

get: function get() {
    return function (data) {
        return template.default;
    };
}
```

I have attempted to set `"inlineExpressions": true`, but it doesn't have any effect that I can see.

**Comment by jridgewell** [comment]
This is due to the "incremental" nature of iDOM. As the methods are call, the DOM _is_ mutated. So:

```js
export default <div>Some Content</div>
```

If we compiled into "normal" iDOM code
```js
export default = (0, _incrementalDom.elementOpen)("div"), // Error is thrown, iDOM not in patch context
    (0, _incrementalDom.text)("Some Content"),
    (0, _incrementalDom.elementClose)("div");
```

Obviously, that's no good. So, we wrap them:

```js
// I'm simplifying the output for brevity
template.default = function _div$wrapper() {
    (0, _incrementalDom.elementOpen)("div");
    (0, _incrementalDom.text)("Some Content");
    return (0, _incrementalDom.elementClose)("div");
};
```

This avoids the error. But now how is that function invoked? Somewhere you have a `iDOM.patch` call, and inside that patch call you'll have some JSX root node:

```js
import template from "./template";
class Component {
  template() {
    // Note we are not doing anything to `template`.
    // We're just passing it in as a child.
    return <root>{template}</root>;
  }

  render() {
    iDOM.patch(this.element, this.template);
  }
}
```

That root node is important. It changes the semantics of everything inside it from "call a function" to "render this variable as a JSX child element".  And we're able to hook into that to render the wrapped `_div$wrapper`.

**Comment by oravecz** [comment]
I suppose there is no means to fully contain the dom in the template without introducing this `<root/>` element? My `Component` is a custom element, so it is declared using something like this:

```html
<my-custom></my-custom>
```

Which ends up rendering:

```html
<my-custom><root><div>Some Content</div></root></my-custom>
```

**Comment by jridgewell** [comment]
Not with the "constant" evaluation you're trying to do. Instead, you could define it like you did initially:

```js
export default () => <div>Some Content</div>;
```
