### ISSUE TITLE
Scoped CSS Styles

### ISSUE THREAD

**Issue by oravecz** [jridgewell/babel-plugin-transform-incremental-dom#88]
Is there any work planned to add support for <style> tags and scoping the generated idom to apply styles in a manner that emulates the native shadow dom capabilities.

Kind of like merging the [zeit/styled-jsx](https://github.com/zeit/styled-jsx) library and this one.

**Comment by jridgewell** [comment]
This looks like it's just a Component, with some unique class names being added to everything in scope?

**Comment by oravecz** [comment]
Yes, I agree. We are using your plugin to author our templates using JSX
and compiling to IDom of course. What is missing is a way of modifying the
AST in a similar way such that we can target styles in the same way that
shadow dom allows.

**Comment by jridgewell** [comment]
Depending on how their transform is architected, it could "just work" with ours. It just needs to run before ours.
